backend:
  name: github
  repo: EricDs6/UEA-LABORATORIO-DE-DINAMICAS-SOCIOAMBIENTAIS
  branch: main
  auth_scope: repo
  open_authoring: false

media_folder: "public/img/uploads"
public_folder: "/img/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: "demopublickey"

publish_mode: editorial_workflow

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "data/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Imagem de capa", name: "cover", widget: "image", required: false }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
