backend:
  name: github
  repo: EricDs6/UEA-LABORATORIO-DE-DINAMICAS-SOCIOAMBIENTAIS
  branch: main
  site_domain: lds-uea.com.br
media_folder: "uploads"
publish_mode: editorial_workflow
collections:
  - name: "noticias"
    label: "Notícias"
    files:
      - label: "Notícias"
        name: "noticias"
        file: "public/data/noticias.json"
        fields:
          - { label: "Título", name: "titulo", widget: "string" }
          - { label: "Resumo", name: "resumo", widget: "text" }
          - { label: "Imagem", name: "imagem", widget: "string", required: false }
